version: '3.4'

services:
  nginx:
    build:
      context: .
      dockerfile: ./.docker/nginx/Dockerfile
    volumes:
      - ./:/var/www/html:cached
      - ./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./.docker/nginx/sites/:/etc/nginx/sites-available
      - ./.docker/nginx/conf.d/:/etc/nginx/conf.d
    depends_on:
      - php
    ports:
      - "80:80"
      - "443:443"
  php:
    build:
      context: .
      dockerfile: ./.docker/php/Dockerfile
    volumes:
      - ./:/var/www/html:cached
    depends_on:
      - database
    environment:
      NETTE_DEBUG: 1
      PHP_EXTENSION_XDEBUG: 1
      PHP_EXTENSION_PGSQL: 1
      PHP_EXTENSION_PDO_PGSQL: 1
      PHP_EXTENSION_MYSQLI: 1
      STARTUP_COMMAND_1: composer install
      STARTUP_COMMAND_2: composer set-config -- config/local.neon \
        --database.host=database \
        --database.user=doctrine \
        --database.password=doctrine \
        --database.dbname=doctrine
      STARTUP_COMMAND_3: NETTE_DEBUG=1 php bin/console migrations:migrate --no-interaction
      STARTUP_COMMAND_4: NETTE_DEBUG=1 php bin/console doctrine:fixtures:load --no-interaction

  database:
    image: dockette/postgres:13
    environment:
      - POSTGRES_PASSWORD=doctrine
      - POSTGRES_USER=doctrine
      - POSTGRES_DB=doctrine
    #volumes:
    #  - .docker/data/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432

  adminer:
    image: dockette/adminer:dg
    ports:
      - 8080:80
